config/routes.rb
Rails.application.routes.draw do

  resources :artists do  #, only: [:index, :new, :create, :show, :edit, :update, :delete]
    resources :songs, only: [:new, :create]
  end

  resources :songs, only: [:show]

end

app/models/artist.rb
class Artist < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true

  has_many :songs

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.create(artist_params)
    if @artist.save
      redirect_to @artist # => redirect_to artist_path(artist)
    else
      render :new
    end
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    @artist.update(artist_params)

    redirect_to @artist #artist_path(@artist)
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to artists_path
  end


private

  def artist_params
    params.require(:artist).permit(:name, :image_path)
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def new
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.create(song_params)

    redirect_to song_path(@song)
  end

  def show
    @song = Song.find(params[:id])
  end


private

  def song_params
    params.require(:song).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/edit.html.erb
<h1>Edit info for <%= @artist.name %></h1>

<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_path %>
  <%= f.text_field :image_path %>

  <%= f.submit %>
<% end %>

app/views/artists/index.html.erb
<h1>All Artists</h1>

<% @artists.each do |artist| %>
  <ul>
    <li><%= link_to artist.name, artist_path(artist) %></li>
  </ul>
<% end %>

<%= link_to "New artist", new_artist_path %>

app/views/artists/new.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_path %>
  <%= f.text_field :image_path %>

  <%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<%= image_tag @artist.image_path %>

</br>
<%= link_to "<< Back to Index", artists_path %></br>
<%= link_to "Edit", edit_artist_path(@artist) %></br>
<%= link_to "Delete", artist_path(@artist), method: :delete %></br>
<%= link_to "New song", new_artist_song_path(@artist) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MixMaster</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/new.html.erb
<h1>New Song</h1>

<p>Add a new Song for <%= @artist.name %></p>

<%= form_for([@artist, @song]) do |f| %>
  <%= f.label :title %></br>
  <%= f.text_field :title %></br>

  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>

<%= link_to @song.artist.name, artist_path(@song.artist) %>